// src/components/MatchList.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Match } from '../match';
import { useMatches } from '../hooks/useMatches';
import { useStore } from '../store/useStore';
import { QRExport } from '../qr';
import { PDFExport } from '../pdf';

interface MatchListProps {
  matches: Match[];
}

export default function MatchList({ matches }: MatchListProps) {
  const navigate = useNavigate();
  const { deleteMatch, duplicateMatch } = useMatches();
  const { setShowQRExportDialog, setCurrentQRExportMatch } = useStore();
  const [expandedMatchId, setExpandedMatchId] = useState<string | null>(null);

  const handleMatchClick = (match: Match) => {
    navigate(`/whiteboard/${match.id}`);
  };

  const handleDeleteMatch = async (e: React.MouseEvent, matchId: string) => {
    e.stopPropagation();
    await deleteMatch(matchId);
    setExpandedMatchId(null);
  };

  const handleDuplicateMatch = async (e: React.MouseEvent, matchId: string) => {
    e.stopPropagation();
    await duplicateMatch(matchId);
    setExpandedMatchId(null);
  };

  const handleExportQR = (e: React.MouseEvent, match: Match) => {
    e.stopPropagation();
    e.preventDefault();
    setExpandedMatchId(null);
    // Set match first, then open dialog
    setCurrentQRExportMatch(match);
    // Use setTimeout to ensure state update propagates
    setTimeout(() => {
      setShowQRExportDialog(true);
    }, 0);
  };

  const handleExportPNG = async (e: React.MouseEvent, match: Match) => {
    e.stopPropagation();
    setExpandedMatchId(null);

    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `strategy-board-${match.matchName}-${timestamp}.png`;

      // Store the export request in sessionStorage
      sessionStorage.setItem('pendingPNGExport', filename);

      // Navigate to whiteboard to render canvases
      navigate(`/whiteboard/${match.id}`);
    } catch (err) {
      console.error('PNG export failed:', err);
      alert('Failed to export PNG. Please try again.');
    }
  };

  const handleExportPDF = async (e: React.MouseEvent, match: Match) => {
    e.stopPropagation();
    setExpandedMatchId(null);

    try {
      const pdfExport = new PDFExport();
      const packet = match.getAsPacket();
      packet.splice(7, 1);
      const raw = JSON.stringify(packet);

      const encoder = new TextEncoder();
      const bytes = encoder.encode(raw);
      let binary = '';
      for (let i = 0; i < bytes.length; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      const b64 = btoa(binary);

      const MAX_CHUNK_PAYLOAD = 200;
      const HEADER_SIZE = 4;
      const TOTAL_CHUNKS_HEADER_SIZE = 4;

      const chunks: string[] = [];
      for (let i = 0; i < b64.length; i += MAX_CHUNK_PAYLOAD) {
        chunks.push(b64.slice(i, i + MAX_CHUNK_PAYLOAD));
      }

      const totalChunks = Math.max(1, chunks.length);
      const payloads: string[] = [];
      for (let i = 0; i < totalChunks; i++) {
        const payload =
          i.toString().padStart(HEADER_SIZE, '0') +
          totalChunks.toString().padStart(TOTAL_CHUNKS_HEADER_SIZE, '0') +
          (chunks[i] || '');
        payloads.push(payload);
      }

      await pdfExport.exportToPDFLarge(payloads, match.matchName);
    } catch (error) {
      console.error('Failed to export PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  const toggleOptions = (e: React.MouseEvent, matchId: string) => {
    e.stopPropagation();
    setExpandedMatchId(expandedMatchId === matchId ? null : matchId);
  };

  return (
    <div id="home-match-list" className="w-full p-6 flex-1 flex flex-col gap-2 items-center overflow-y-auto bg-slate-800">
      {matches.length === 0 ? (
        <div className="absolute top-1/2 text-slate-300 text-base sm:text-lg md:text-xl italic pointer-events-none">
          Click <span className="not-italic text-white bg-green-500 px-2 py-1 rounded-lg">New</span> to add matches
        </div>
      ) : (
        matches.map((match) => (
          <div
            key={match.id}
            className="w-full h-20 sm:h-22 md:h-24 bg-slate-700 flex shrink-0 justify-between items-center rounded-xl glass-card px-4 sm:px-6 md:px-8 cursor-pointer hover:bg-slate-600 transition-colors"
            onClick={() => handleMatchClick(match)}
            tabIndex={0}
            role="button"
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                handleMatchClick(match);
              }
            }}
            onBlur={(e) => {
              if (!e.currentTarget.contains(e.relatedTarget as Node)) {
                setExpandedMatchId(null);
              }
            }}
          >
            <div className="grow-1 basis-0 text-slate-200 font-bold text-base sm:text-lg md:text-xl lg:text-2xl select-none overflow-hidden text-ellipsis whitespace-nowrap">
              {match.matchName || 'Untitled'}
            </div>
            <div className="w-1/2 flex justify-center items-center gap-2 sm:gap-4 md:gap-6">
              <div className="w-1/2 text-red-400 text-sm sm:text-base md:text-lg lg:text-2xl text-right select-none overflow-hidden text-ellipsis whitespace-nowrap">
                {match.redThree || '---'} {match.redTwo || '---'} {match.redOne || '---'}
              </div>
              <div className="text-slate-200 text-sm sm:text-base md:text-lg lg:text-2xl select-none">
                VS
              </div>
              <div className="w-1/2 text-blue-400 text-sm sm:text-base md:text-lg lg:text-2xl select-none overflow-hidden text-ellipsis whitespace-nowrap">
                {match.blueOne || '---'} {match.blueTwo || '---'} {match.blueThree || '---'}
              </div>
            </div>
            <div className="grow-1 basis-0 flex h-full justify-end items-center">
              {expandedMatchId !== match.id ? (
                <button
                  className="flex flex-col w-8 sm:w-10 md:w-12 gap-1 items-center justify-center"
                  onClick={(e) => toggleOptions(e, match.id)}
                >
                  <div className="w-1.5 h-1.5 sm:w-2 sm:h-2 rounded-full bg-white"></div>
                  <div className="w-1.5 h-1.5 sm:w-2 sm:h-2 rounded-full bg-white"></div>
                  <div className="w-1.5 h-1.5 sm:w-2 sm:h-2 rounded-full bg-white"></div>
                </button>
              ) : (
                <div className="flex items-center justify-center gap-2" onClick={(e) => e.stopPropagation()}>
                  <button
                    className="w-24 sm:w-32 p-1 sm:p-2 text-xs sm:text-sm md:text-base lg:text-xl text-white bg-green-500 rounded-xl glass-button glossy-shine"
                    onClick={(e) => handleDuplicateMatch(e, match.id)}
                  >
                    Duplicate
                  </button>
                  <button
                    className="w-24 sm:w-32 p-1 sm:p-2 text-xs sm:text-sm md:text-base lg:text-xl text-white bg-blue-500 rounded-xl glass-button glossy-shine whitespace-nowrap"
                    onClick={(e) => handleExportQR(e, match)}
                  >
                    Export QR
                  </button>
                  <button
                    className="w-24 sm:w-32 p-1 sm:p-2 text-xs sm:text-sm md:text-base lg:text-xl text-white bg-cyan-500 rounded-xl glass-button glossy-shine whitespace-nowrap"
                    onClick={(e) => handleExportPNG(e, match)}
                  >
                    Export PNG
                  </button>
                  <button
                    className="w-24 sm:w-32 p-1 sm:p-2 text-xs sm:text-sm md:text-base lg:text-xl text-white bg-purple-500 rounded-xl glass-button glossy-shine whitespace-nowrap"
                    onClick={(e) => handleExportPDF(e, match)}
                  >
                    Export PDF
                  </button>
                  <button
                    className="w-20 sm:w-24 p-1 sm:p-2 text-xs sm:text-sm md:text-base lg:text-xl text-white bg-red-500 rounded-xl glass-button glossy-shine"
                    onClick={(e) => handleDeleteMatch(e, match.id)}
                  >
                    Delete
                  </button>
                </div>
              )}
            </div>
          </div>
        ))
      )}
    </div>
  );
}

// src/lib/components/MatchList.svelte
<script lang="ts">
  import { loadContributorTeams } from "$lib/features";
  import type { Match } from "./types";

  let { matches, onOpen, onEdit, onDuplicate, onExportPng, onExportQr, onShare, onDelete }: { matches: Match[]; onOpen: (match: Match) => void; onEdit: (match: Match) => void; onDuplicate: (match: Match) => void; onExportPng: (match: Match) => void; onExportQr: (match: Match) => void; onShare: (match: Match) => void; onDelete: (match: Match) => void } = $props();

  const GOLD_TEAM = "834";
  let openId = $state<string | null>(null);
  let contributorTeams = $state<string[]>([]);

  $effect(() => { void loadContributorTeams().then((teams) => (contributorTeams = teams), () => {}); });

  /** Matches the original: team 834 pulses gold, contributor teams cycle rainbow. */
  function animationOf(team: string): "rainbow" | "gold" | "none" {
    if (team === GOLD_TEAM) return "gold";
    if (contributorTeams.includes(team)) return "rainbow";
    return "none";
  }

  // Red is listed right-to-left so the alliances mirror across the "VS" divider.
  const redTeams = (match: Match) => [match.redThree, match.redTwo, match.redOne];
  const blueTeams = (match: Match) => [match.blueOne, match.blueTwo, match.blueThree];

  function open(match: Match) { if (openId !== match.id) onOpen(match); }
  function closeActions(event: FocusEvent) {
    const item = event.currentTarget as HTMLElement;
    if (item.contains(event.relatedTarget as Node)) return;
    openId = null;
  }
  function run(action: (match: Match) => void, match: Match) { openId = null; action(match); }
</script>

{#snippet teamList(teams: string[], baseColor: string)}
  {#each teams as team, teamIndex}{#if teamIndex > 0}{" "}{/if}<span class={baseColor}
    >{#if animationOf(team) === "none"}{team}{:else}{#each team.split("") as digit, digitIndex}<span
          class={animationOf(team) === "rainbow" ? "rainbow-team-digit" : "special-team-digit"}
          style="animation-delay: {digitIndex * 0.3}s;">{digit}</span
        >{/each}{/if}</span
  >{/each}
{/snippet}

<div
  id="home-match-list"
  class="w-full p-10 flex-1 flex flex-col gap-3 items-stretch overflow-y-auto bg-[#0d0d0d]"
  class:match-list-actions-open={openId !== null}
>
  {#if matches.length === 0}
    <div id="home-match-list-empty-placeholder" class="absolute top-1/2 text-[#999] text-xl pointer-events-none">
      Click
      <span class="not-italic text-[#999] bg-[#1a1a1a] border border-[#2a2a2a] px-3 py-1 rounded">New</span>
      to add matches
    </div>
  {/if}
  {#each matches as match (match.id)}
    <div
      class="w-full h-[5.5rem] bg-[#141414] border border-[#1e1e1e] flex shrink-0 justify-between items-center rounded-xl px-10"
      class:match-actions-open={openId === match.id}
      tabindex="0"
      role="button"
      onclick={() => open(match)}
      onkeydown={(event) => { if (event.key === "Enter") open(match); }}
      onfocusout={closeActions}
    >
      <div class="grow-1 basis-0 text-[#e8e8e8] font-semibold text-2xl select-none overflow-hidden text-ellipsis whitespace-nowrap">
        {match.matchName}
      </div>
      <div class="w-1/2 flex justify-center items-center gap-3 sm:gap-5 md:gap-8">
        <div class="w-1/2 text-[#c97070] text-xl text-right select-none overflow-hidden text-ellipsis whitespace-nowrap">
          {@render teamList(redTeams(match), "text-red-400")}
        </div>
        <div class="text-[#999] text-xl select-none">VS</div>
        <div class="w-1/2 text-[#6090c9] text-xl select-none overflow-hidden text-ellipsis whitespace-nowrap">
          {@render teamList(blueTeams(match), "text-blue-400")}
        </div>
      </div>
      <div class="grow-1 basis-0 flex h-full justify-end items-center">
        {#if openId !== match.id}
          <button
            class="match-menu-btn flex flex-col w-14 sm:w-16 md:w-18 gap-2.5 items-center justify-center rounded"
            onclick={(event) => { event.stopPropagation(); openId = match.id; }}
            aria-label={`Actions for ${match.matchName}`}
          >
            <div class="menu-dot w-2.5 h-2.5 rounded-full bg-[#555]"></div>
            <div class="menu-dot w-2.5 h-2.5 rounded-full bg-[#555]"></div>
            <div class="menu-dot w-2.5 h-2.5 rounded-full bg-[#555]"></div>
          </button>
        {:else}
          <div class="flex items-center justify-center gap-3 sm:gap-4" onclick={(event) => event.stopPropagation()} role="presentation">
            <button class="px-5 py-2.5 text-base btn-secondary" onclick={() => run(onEdit, match)}>Edit</button>
            <button class="px-5 py-2.5 text-base btn-secondary" onclick={() => run(onDuplicate, match)}>Duplicate</button>
            <button class="px-5 py-2.5 text-base btn-secondary whitespace-nowrap" onclick={() => run(onExportPng, match)}>Export PNG</button>
            <button class="px-5 py-2.5 text-base btn-secondary whitespace-nowrap" onclick={() => run(onExportQr, match)}>Export QR</button>
            <button class="px-5 py-2.5 text-base btn-secondary whitespace-nowrap flex items-center gap-2" onclick={() => run(onShare, match)}>
              <span>Share</span>
              <i class="fas fa-link text-lg"></i>
            </button>
            <button class="px-5 py-2.5 text-base btn-danger" onclick={() => run(onDelete, match)}>Delete</button>
          </div>
        {/if}
      </div>
    </div>
  {/each}
</div>
